version: "3.3"

services:
  nginx:
    image: nginx:1.14.2
    links:
      - app:app
    ports:
      - "8001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  app:
    build: oracles
    image: oracles:0.2.9
    environment:
      - FLASK_DEBUG=1
    ports:
      - "3031:3031"
