# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
# orb instructions at https://circleci.com/orbs/registry/orb/codecov/codecov
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: cimg/python:3.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt-get update && sudo apt-get install libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libatspi2.0-0 \
            libxdamage1 \
            libgbm1 \
            libxkbcommon0 \
            libpango-1.0-0 \
            libcairo2 \
            libasound2
            poetry install
            poetry run playwright install

      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
          key: v1-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: run tests
          command: |
            poetry run pytest --cov=./ --cov-report xml

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - codecov/upload:
          file: coverage.xml
